# Generated by Django 4.1.2 on 2022-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default='unknown user', max_length=1000),
        ),
    ]
