# Generated by Django 4.1.2 on 2022-11-03 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_message_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.IntegerField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.CharField(max_length=1000),
        ),
    ]
